Fix Travis::Client::Methods spec after transpec
transpec left three failing examples in the Travis::Client::Methods spec:

    Failures:

      1) Travis::Client::Methods#api_endpoint
         Failure/Error: before { subject.access_token = 'token' }
         NoMethodError:
           undefined method `access_token=' for "https://api.travis-ci.org/":String
         # ./spec/client/methods_spec.rb:6:in `block (2 levels) in <top (required)>'

      2) Travis::Client::Methods#repos
         Failure/Error: before { subject.access_token = 'token' }
         NoMethodError:
           undefined method `access_token=' for [#<Travis::Client::Repository: pypug/django-mango>]:Array
         # ./spec/client/methods_spec.rb:6:in `block (2 levels) in <top (required)>'

      3) Travis::Client::Methods#user
         Failure/Error: subject { super().user }
         Travis::Client::NotLoggedIn:
           invalid access token
         # ./lib/travis/client/session.rb:219:in `raw'
         # ./lib/travis/client/session.rb:184:in `get_raw'
         # ./lib/travis/client/session.rb:164:in `get'
         # ./lib/travis/client/session.rb:317:in `fetch_one'
         # ./lib/travis/client/session.rb:95:in `block in find_one'
         # ./lib/travis/client/session.rb:327:in `cached'
         # ./lib/travis/client/session.rb:95:in `find_one'
         # ./lib/travis/client/methods.rb:56:in `user'
         # ./spec/client/methods_spec.rb:19:in `block (3 levels) in <top (required)>'
         # ./spec/client/methods_spec.rb:6:in `block (2 levels) in <top (required)>'

This is due to changes in how `subject` is handled in `before`
blocks. Switching the `before` to set call `#auth_token` on the session
object directly affects the same change and gets around the issue.