Fix the gem install command in the readme
The `gem --no-rdoc` and `--no-ri` switches are deprecated:

```
$ gem install travis -v 1.8.10 --no-rdoc --no-ri
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --no-rdoc
$ gem --version
3.0.6
```

This commit updates the installation instructions in the readme with the new syntax.